#!/usr/bin/python3

import pop.hub

CONFIG = {
        'seed_name': {
            'default': 'tester_test',
            'help': 'The name of the project that is being created'
            },
        }

hub = pop.hub.Hub()
hub.tools.sub.add('conf', pypath='pop.mods.conf')
hub.opts = hub.conf.reader.read(CONFIG)
print(hub.opts)
hub.tools.seed.new()
